# Generated by Django 5.2.5 on 2025-08-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='book',
            name='video',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
